{% set name = "pegen" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pegen-{{ version }}.tar.gz
  sha256: 8cb30cee508a95c573aa256ed2cfa80ef8f561b90264c70e7de5afc50b4ac87d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - wheel
    - setuptools-scm >=3.4.3
    - pip
  run:
    - python >={{ python_min }},<4.0

test:
  imports:
    - pegen
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: CPython's PEG parser generator
  license: MIT
  license_file: LICENSE
  home: https://we-like-parsers.github.io/pegen/

extra:
  recipe-maintainers:
    - gabrielcnr
    - MatthieuDartiailh
    - marcelotrevisani
